## **1) Data Preprocessing**
- Import packages and dataset
- Handling Missing Values
- Handling Duplicates
- Checking and Fixing the datatypes
- Understand the dataset

**1.1 Import Packages and dataset**

In [292]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings as wn

wn.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

# Create a Dataframe
data = pd.read_csv("data/churn-data.csv")
# Shape of the dataset
print(data.shape)

(7043, 21)

**1.2 Handling Missing Values**

In [293]:
## Checking missing values 
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

- There are **no null values** in the dataset.

**1.3 Handling Duplicates**

In [294]:
data.duplicated().sum()

np.int64(0)

- **No duplicates** in the dataset.

**1.4 Checking and Fixing Datatypes**

In [295]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [296]:
data.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [297]:
# Converting TotalCharges str to float type
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")

In [298]:
data.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [299]:
data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

- There are some null values in **TotalCharges** after converting it to float type.
- Drop the missing values.

In [300]:
data = data.dropna()

In [301]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

**1.5 Dropping the customerID column which is not important**

In [302]:
data = data.drop("customerID", axis=1)

In [303]:
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [304]:
# Transforming columns with having category like "No phone Service or No internet Service" to "No"
columns_to_transform = ["MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection",
                        "TechSupport","StreamingTV","StreamingMovies"]

for col in columns_to_transform :
    data[col] = data[col].str.replace("No phone service", "No").str.replace("No internet service", "No")

In [305]:
for col in columns_to_transform:
    print(data[col].value_counts())

MultipleLines
No     4065
Yes    2967
Name: count, dtype: int64
OnlineSecurity
No     5017
Yes    2015
Name: count, dtype: int64
OnlineBackup
No     4607
Yes    2425
Name: count, dtype: int64
DeviceProtection
No     4614
Yes    2418
Name: count, dtype: int64
TechSupport
No     4992
Yes    2040
Name: count, dtype: int64
StreamingTV
No     4329
Yes    2703
Name: count, dtype: int64
StreamingMovies
No     4301
Yes    2731
Name: count, dtype: int64

## **2) Feature Engineering**

**2.1 Splitting the Features**

In [306]:
X = data.drop("Churn",axis=1)
y = data["Churn"]

**2.2 Feature Selection**

In [307]:
# Creating New Feature

# 1. Total Services Count
services = ["OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"]
X["Total_Services_Count"] = X[services].apply(lambda x: np.where(x=="Yes", 1, 0)).apply(lambda row: (row > 0).sum(), axis=1)

# 2. Average Monthly Charges
X["Historical_Monthly_Charges"] = round(X["TotalCharges"] / X["tenure"], 2)

In [308]:
# 3. Charge Spike 
X["Charge_Spike"] = X["MonthlyCharges"] - X["Historical_Monthly_Charges"]

# 4. Total_Security_Tech_Services
security = ["OnlineSecurity", "OnlineBackup"]
X["Total_Security_Tech_Services"] = X[security].apply(lambda x: np.where(x=="Yes", 1, 0)).apply(lambda row: (row > 0).sum(), axis=1)

In [309]:
# 5. Total Streaming Services
streaming = ["StreamingTV", "StreamingMovies"]
X["TotalStreamingServices"] = X[streaming].apply(lambda x: np.where(x=="Yes", 1, 0)).apply(lambda row: (row > 0).sum(), axis=1)

# 6. Is_Family
X["Is_Family"] = np.where((X["Dependents"] == "Yes") | (X["Partner"] == "Yes"), 1, 0)

# 7. Is_Autopay
X["Is_Autopay"] = np.where(X["PaymentMethod"].str.contains("auto"), 1, 0)

# 8. Tenure_Group
def tenure_group(tenure):
    if tenure <= 6 :
        return "0-6 months (New)"
    elif  6 < tenure <= 24:
        return "6-24 months"
    elif 24 < tenure <= 60:
        return "24-60 months"
    else :
        return "60+ months"

X["Tenure_Group"] = X["tenure"].apply(tenure_group)

In [310]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Total_Services_Count,Historical_Monthly_Charges,Charge_Spike,Total_Security_Tech_Services,TotalStreamingServices,Is_Family,Is_Autopay,Tenure_Group
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1,29.85,0.00,1,0,1,0,0-6 months (New)
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,2,55.57,1.38,1,0,0,0,24-60 months
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,2,54.08,-0.23,2,0,0,0,0-6 months (New)
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,3,40.91,1.39,1,0,0,1,24-60 months
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,75.82,-5.12,0,0,0,0,0-6 months (New)

In [311]:
X = X.drop(columns = ["gender", "PhoneService", "TotalCharges", "StreamingTV", "StreamingMovies", "OnlineSecurity", "OnlineBackup", ])

In [312]:
X.head()

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,InternetService,DeviceProtection,TechSupport,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Total_Services_Count,Historical_Monthly_Charges,Charge_Spike,Total_Security_Tech_Services,TotalStreamingServices,Is_Family,Is_Autopay,Tenure_Group
0,0,Yes,No,1,No,DSL,No,No,Month-to-month,Yes,Electronic check,29.85,1,29.85,0.00,1,0,1,0,0-6 months (New)
1,0,No,No,34,No,DSL,Yes,No,One year,No,Mailed check,56.95,2,55.57,1.38,1,0,0,0,24-60 months
2,0,No,No,2,No,DSL,No,No,Month-to-month,Yes,Mailed check,53.85,2,54.08,-0.23,2,0,0,0,0-6 months (New)
3,0,No,No,45,No,DSL,Yes,Yes,One year,No,Bank transfer (automatic),42.30,3,40.91,1.39,1,0,0,1,24-60 months
4,0,No,No,2,No,Fiber optic,No,No,Month-to-month,Yes,Electronic check,70.70,0,75.82,-5.12,0,0,0,0,0-6 months (New)

In [313]:
X.dtypes

SeniorCitizen                     int64
Partner                             str
Dependents                          str
tenure                            int64
MultipleLines                       str
InternetService                     str
DeviceProtection                    str
TechSupport                         str
Contract                            str
PaperlessBilling                    str
PaymentMethod                       str
MonthlyCharges                  float64
Total_Services_Count              int64
Historical_Monthly_Charges      float64
Charge_Spike                    float64
Total_Security_Tech_Services      int64
TotalStreamingServices            int64
Is_Family                         int64
Is_Autopay                        int64
Tenure_Group                        str
dtype: object

In [314]:
numerical_features = [feature for feature in X.columns if X[feature].dtype != "str"]
categorical_features = [feature for feature in X.columns if X[feature].dtype == "str"]
discrete_features = [feature for feature in X.columns if X[feature].nunique() < 25]
continuous_features = [feature for feature in X.columns if X[feature].nunique() >= 25]

print(f"We have {len(numerical_features)} numerical features : {numerical_features}")
print(f"We have {len(categorical_features)} categorical features : {categorical_features}")
print(f"We have {len(discrete_features)} discrete features : {discrete_features}")
print(f"We have {len(continuous_features)} continuous features : {continuous_features}")

We have 10 numerical features : ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'Total_Services_Count', 'Historical_Monthly_Charges', 'Charge_Spike', 'Total_Security_Tech_Services', 'TotalStreamingServices', 'Is_Family', 'Is_Autopay']
We have 10 categorical features : ['Partner', 'Dependents', 'MultipleLines', 'InternetService', 'DeviceProtection', 'TechSupport', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Tenure_Group']
We have 16 discrete features : ['SeniorCitizen', 'Partner', 'Dependents', 'MultipleLines', 'InternetService', 'DeviceProtection', 'TechSupport', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Total_Services_Count', 'Total_Security_Tech_Services', 'TotalStreamingServices', 'Is_Family', 'Is_Autopay', 'Tenure_Group']
We have 4 continuous features : ['tenure', 'MonthlyCharges', 'Historical_Monthly_Charges', 'Charge_Spike']

**2.3 Feature Encoding and Scaling**

In [315]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer


transformer = ColumnTransformer(transformers= [
    ("oh_tf", OneHotEncoder(drop="first"), categorical_features),
    ("scaler_tf", StandardScaler(), continuous_features)
], remainder="passthrough")

In [316]:
X = transformer.fit_transform(X)

In [317]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.280248,-1.161694,-1.157887,0.000452,0.0,1.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.064303,-0.260878,-0.305773,0.527988,0.0,2.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.239504,-0.363923,-0.355138,-0.087471,0.0,2.0,2.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.512486,-0.747850,-0.791465,0.531810,0.0,3.0,1.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.239504,0.196178,0.365117,-1.956783,0.0,0.0,0.0,0.0,0.0,0.0

In [318]:
# Label Encoding for Output Feature
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [319]:
y

array([0, 0, 1, ..., 0, 1, 0], shape=(7032,))

**2.4 Handling Class Imbalance using SMOTE Technique**

In [320]:
# Handling Class Imbalance
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy="minority", random_state=1)
X_res, y_res = smote.fit_resample(X, y)

## **3) Model Training**

In [321]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix, \
                            precision_score, recall_score, f1_score, roc_auc_score

In [322]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape, X_test.shape

((4922, 26), (2110, 26))

In [323]:
def evaluate_models(true, pred) :
    accuracy = accuracy_score(true, pred)
    report = classification_report(true, pred)
    matrix = confusion_matrix(true, pred)
    precision = precision_score(true, pred)
    recall = recall_score(true, pred)
    f1 = f1_score(true, pred)
    roc_score = roc_auc_score(true, pred)

    return accuracy, report, matrix, precision, recall, f1, roc_score

**Model Training where SMOTE is applied to the dataset**

In [324]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((8260, 26), (2066, 26))

In [325]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "DecisionTreeClassifier" : DecisionTreeClassifier(),
    "KNeighborsClassifier" : KNeighborsClassifier(),
    "AdaBoost" : AdaBoostClassifier(),
    "Gradient Boost" : GradientBoostingClassifier(),
}
model_list = []
acc_list = []
for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_acc, train_report, train_matrix, train_precision, train_recall, train_f1, train_roc = evaluate_models(y_train, y_train_pred)
    test_acc, test_report, test_matrix, test_precision, test_recall, test_f1, test_roc = evaluate_models(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    print("Model Performance for Training Set")
    print(f"Accuracy Score: {train_acc:.4f}")
    print(f"Classification Report: \n{train_report}")
    print(f"Confusion Matrix: \n{train_matrix}")
    print(f"Precision Score: {train_precision:.4f}")
    print(f"Recall Score: {train_recall:.4f}")
    print(f"F1 Score: {train_f1:.4f}")
    print(f"ROc Score: {train_roc:.4f}")

    print("--------------------------------------------")
    print("Model Performance for Test Set")
    print(f"Accuracy Score: {test_acc:.4f}")
    print(f"Classification Report: \n {test_report}")
    print(f"Confusion Matrix: \n{test_matrix}")
    print(f"Precision Score: {test_precision:.4f}")
    print(f"Recall Score: {test_recall:.4f}")
    print(f"F1 Score: {test_f1:.4f}")
    print(f"ROc Score: {test_roc:.4f}")

    print("="*50)
    print("\n")
    model_list.append(list(models.keys())[i])
    acc_list.append(test_acc)

Logistic Regression
Model Performance for Training Set
Accuracy Score: 0.7719
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.74      0.76      4126
           1       0.76      0.80      0.78      4134

    accuracy                           0.77      8260
   macro avg       0.77      0.77      0.77      8260
weighted avg       0.77      0.77      0.77      8260

Confusion Matrix:
[[3057 1069]
 [ 815 3319]]
Precision Score: 0.7564
Recall Score: 0.8029
F1 Score: 0.7789
ROc Score: 0.7719
--------------------------------------------
Model Performance for Test Set
Accuracy Score: 0.7880
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.74      0.78      1037
           1       0.76      0.83      0.80      1029

    accuracy                           0.79      2066
   macro avg       0.79      0.79      0.79      2066
weighted avg       0.79      0.79      0.79      2066

Confusion Matrix:
[[772 265]
 [173 856]]
Precision Score: 0.7636
Recall Score: 0.8319
F1 Score: 0.7963
ROc Score: 0.7882
==================================================


DecisionTreeClassifier
Model Performance for Training Set
Accuracy Score: 0.9984
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4126
           1       1.00      1.00      1.00      4134

    accuracy                           1.00      8260
   macro avg       1.00      1.00      1.00      8260
weighted avg       1.00      1.00      1.00      8260

Confusion Matrix:
[[4123    3]
 [  10 4124]]
Precision Score: 0.9993
Recall Score: 0.9976
F1 Score: 0.9984
ROc Score: 0.9984
--------------------------------------------
Model Performance for Test Set
Accuracy Score: 0.7928
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.78      0.79      1037
           1       0.79      0.80      0.79      1029

    accuracy                           0.79      2066
   macro avg       0.79      0.79      0.79      2066
weighted avg       0.79      0.79      0.79      2066

Confusion Matrix:
[[811 226]
 [202 827]]
Precision Score: 0.7854
Recall Score: 0.8037
F1 Score: 0.7944
ROc Score: 0.7929
==================================================


KNeighborsClassifier
Model Performance for Training Set
Accuracy Score: 0.8557
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.76      0.84      4126
           1       0.80      0.95      0.87      4134

    accuracy                           0.86      8260
   macro avg       0.87      0.86      0.85      8260
weighted avg       0.87      0.86      0.85      8260

Confusion Matrix:
[[3140  986]
 [ 206 3928]]
Precision Score: 0.7993
Recall Score: 0.9502
F1 Score: 0.8683
ROc Score: 0.8556
--------------------------------------------
Model Performance for Test Set
Accuracy Score: 0.7977
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.68      0.77      1037
           1       0.74      0.91      0.82      1029

    accuracy                           0.80      2066
   macro avg       0.81      0.80      0.80      2066
weighted avg       0.81      0.80      0.80      2066

Confusion Matrix:
[[710 327]
 [ 91 938]]
Precision Score: 0.7415
Recall Score: 0.9116
F1 Score: 0.8178
ROc Score: 0.7981
==================================================


AdaBoost
Model Performance for Training Set
Accuracy Score: 0.8027
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.77      0.80      4126
           1       0.78      0.84      0.81      4134

    accuracy                           0.80      8260
   macro avg       0.80      0.80      0.80      8260
weighted avg       0.80      0.80      0.80      8260

Confusion Matrix:
[[3169  957]
 [ 673 3461]]
Precision Score: 0.7834
Recall Score: 0.8372
F1 Score: 0.8094
ROc Score: 0.8026
--------------------------------------------
Model Performance for Test Set
Accuracy Score: 0.8064
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.76      0.80      1037
           1       0.78      0.85      0.81      1029

    accuracy                           0.81      2066
   macro avg       0.81      0.81      0.81      2066
weighted avg       0.81      0.81      0.81      2066

Confusion Matrix:
[[791 246]
 [154 875]]
Precision Score: 0.7806
Recall Score: 0.8503
F1 Score: 0.8140
ROc Score: 0.8066
==================================================


Gradient Boost
Model Performance for Training Set
Accuracy Score: 0.8573
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.84      0.85      4126
           1       0.84      0.88      0.86      4134

    accuracy                           0.86      8260
   macro avg       0.86      0.86      0.86      8260
weighted avg       0.86      0.86      0.86      8260

Confusion Matrix:
[[3449  677]
 [ 502 3632]]
Precision Score: 0.8429
Recall Score: 0.8786
F1 Score: 0.8604
ROc Score: 0.8572
--------------------------------------------
Model Performance for Test Set
Accuracy Score: 0.8475
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.82      0.84      1037
           1       0.83      0.87      0.85      1029

    accuracy                           0.85      2066
   macro avg       0.85      0.85      0.85      2066
weighted avg       0.85      0.85      0.85      2066

Confusion Matrix:
[[851 186]
 [129 900]]
Precision Score: 0.8287
Recall Score: 0.8746
F1 Score: 0.8511
ROc Score: 0.8476
==================================================

In [326]:
print(model_list)
print(acc_list)

model_df = pd.DataFrame({"Model": model_list, "Accuracy": acc_list}).sort_values("Accuracy", ascending=False)
model_df

['Logistic Regression', 'DecisionTreeClassifier', 'KNeighborsClassifier', 'AdaBoost', 'Gradient Boost']
[0.7879961277831559, 0.7928363988383349, 0.797676669893514, 0.8063891577928364, 0.8475314617618587]

                    Model  Accuracy
4          Gradient Boost  0.847531
3                AdaBoost  0.806389
2    KNeighborsClassifier  0.797677
1  DecisionTreeClassifier  0.792836
0     Logistic Regression  0.787996